### ISSUE TITLE
Embedding GeoJSON

### ISSUE THREAD

**Issue by a-knudsen** [a-knudsen/a-knudsen.github.io#1] opened 2020-03-27 18:15 UTC
I'm having trouble embedding my GeoJSON file. I copied the format from https://help.github.com/en/github/managing-files-in-a-repository/mapping-geojson-files-on-github#embedding-your-map-elsewhere
<script src="https://embed.github.com/view/geojson/<username>/<repo>/<ref>/<path_to_file>"></script>

However, my website (https://a-knudsen.github.io/) just has a blank map where the GeoJSON should be. I haven't changed the default width/height but I don't think that's the issue. 
@shadrock @verma-priyanka

**Comment by Shadrock** [comment] 2020-03-27 18:21
Thanks @a-knudsen : can you send a link to the repo that contain the data? I see on your website that the GeoJSON frame is there, but that it isn't showing the data. When I click on the frame to look at the data themselves in a rep, I get a "404" page, which means there isn't any file there.

**Comment by Shadrock** [comment] 2020-03-27 18:41
Aha... sorry, I found it. I believe [**this is it**](https://github.com/a-knudsen/a-knudsen.github.io/blob/master/newenglandcapitals.geojson), right? 

Looks like the issue is the [`src` code in line 26 of the `index.html` file](https://github.com/BaldwinEli/BaldwinEli.github.io/blob/master/maps/index.html). 

- Your source code is `https://github.com/a-knudsen/a-knudsen.github.io/blob/master/newenglandcapitals.geojson` 
- I believe it needs to be `https://github.com/a-knudsen/a-knudsen.github.io/master/newenglandcapitals.geojson`
- The trouble is leaving that `blob` in there!

**Comment by Shadrock** [comment] 2020-03-30 16:56
Ahna, the repo looks good! I appreciate you playing around with some of the fonts and colors. Feel free to close this issue!

**Closed** 2020-04-01 17:08 UTC
